spring:
  datasource:
    url: jdbc:mysql://localhost:3306/std_man_system
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080


#  swagger link for frontEnd developers(before run project) - http://localhost:8080/swagger-ui/index.html#/

